### ISSUE TITLE
Can you explain what is it?

### ISSUE THREAD

**Issue by seekerquoc** [LupeCode/phpTraderInterface#3]
Hello,

Thank you for your project. i have used it but i dont understand what return:

array(90) {
  [10]=>
  float(0)
  [11]=>
  float(100)
  [12]=>
  float(0)
  [13]=>

can you explain?

Thank You

**Comment by jb-lopez** [comment]
This package is a interface to the Trader PECL library.  The point of this package is to provide auto-complete for IDEs and some documentation when using the Trader PECL library.

Please check the PECL package page here: https://pecl.php.net/package/trader
Please check the PHP documentation page here: https://secure.php.net/manual/en/intro.trader.php

You have not provided enough information where I can really answer your question.  I do not know which function you have used, but it looks like you used one of the candle pattern recognition functions.  So, here is some general help.

The return from the trader functions sometimes have a delay before their output.  By that I mean your post appears to start at index 10 instead of 0.  It took the function you used 10 periods to "warm up".  If you were to apply the trader function results on a graph of the stock data, this function would begin to show up at period 10.

It looks like period 11 has a return of 100.  The candle pattern recognition functions will return either 100 when that pattern has occurred, and it is a bullish pattern, or -100 if it is bearish.

**Comment by jb-lopez** [comment]
Closing stale issue.
